Unit-test and jacoco report
MaxwellDevelopments/Diplom-1 pull request #1
Opened 2024-05-25 16:22 UTC by MaxwellDevelopments

added unit-tests for classes Ingredient, Burger, Bun, IngredientType. added jacoco report about code coverage

2024-05-30 19:01 UTC, pavel-ulan requested changes
есть несколько "странных" решений, но в целом все довольно неплохо. Глянь комменты, поправь (лучше поправь все) и будет ок

2024-05-30 19:01 UTC, pavel-ulan commented on src/test/java/BunTests.java
> +    }
скажем так.... внезапно 🤔
очень интересная реализация. как демонстрация работы с дженерик типами - вполне валидно, но как реализация доп слоя для проверки, нуууу. сомнительно.
Не скажу, что это явная ошибка, но все же так лучше не делать. доп слой, который ничего не делает, это только усложняет код и может стать причиной доп ошибок. Я советую убрать, конечно

2024-05-30 19:01 UTC, pavel-ulan commented on src/test/java/BurgerTests.java
> +    IngredientType ing2Type;
**можно лучше**
есть в java принятый порядок. сначала идут импорты, потом класс, внутри константы, паблик, затем приватные поля, потом уже паблик и в конце приватные методы. "прятать" где-то между методами поля, это очень плохо.

2024-05-30 19:01 UTC, pavel-ulan commented on src/test/java/Global.java
> +    private Global() {
**можно лучше**
и зачем тебе тут такая конструкция? у тебя не синглтон, что бы приватный конструктор делать, а статичные методы можно и так вызывать. Просто убери его и ничего не поменяется

2024-05-30 19:01 UTC, pavel-ulan commented on src/test/java/IngredientTypeTests.java
> +    String[] VALUES = {
**надо исправить**
Не, ошибки нейминга в дипломе, это уже критично.
в UPPER_CASE именуются только константы. у тебя ни values ни ingredientTypeLength таковыми не являются

2024-06-04 08:44 UTC, MaxwellDevelopments commented on src/test/java/Global.java
> +    private Global() {
Это я сделал, чтобы оградить класс от создания. С другой стороны зачем ограничивать его создание? Наверное какой-то принципиальной мотивации действительно нет.

2024-06-04 08:46 UTC, MaxwellDevelopments commented on src/test/java/IngredientTypeTests.java
> +    String[] VALUES = {
Это не ошибка нейминга, это я забыл final добавить)

2024-06-04 08:49 UTC, MaxwellDevelopments commented on src/test/java/BurgerTests.java
> +    IngredientType ing2Type;
Понял. У меня идея была в том, чтобы при просмотре класса сразу было видно по расположению полей к какому тесту они относятся.

2024-06-04 08:50 UTC, MaxwellDevelopments commented on src/test/java/BunTests.java
> +    }
Ладно!

2024-06-06 18:36 UTC, pavel-ulan commented on src/test/java/BurgerTests.java
> +    IngredientType ing2Type;
идея ок, но все же лучше придерживаться правильной структуры. Эти подходы были выработаны в течении долгого времени (да, есть холивар про clean code и т.п. но все же большинство компаний придерживается этих правил =) )

2024-06-06 18:37 UTC, pavel-ulan approved these changes
Во, все успел поправить, молодцом =)

2024-06-08 09:43 UTC, merged